### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by sidtechnical** [thewhitetulip/pyfox#1]
It seems like there are some issues for me:
I cannot see the `ffs_main.py` file. So, I assume I have to run the `pyfox.py` file. With or without any arguments, I get the `list index out of range` error. 
If would be very useful if you can update the README.md file with correct usage.

**Comment by thewhitetulip** [comment]
Did you try `python3 pyfox.py -b True`?

I did not know that pyfox was actually used by someone :D

I have updated the file name, let me check on the `index out of range error` later today.

**Comment by sidtechnical** [comment]
One man's trash is other man's treasure. So you never know ;) 

Of course I did execute by changing the filename, but the error persists. I too will have a look at the script later. I am sure it is some small fix, which is why I thought you might know it already.

**Comment by thewhitetulip** [comment]
To be honest, I ran it a long time ago, so I do not know what's up with it now :D. I'll look into it and comment here

**Comment by thewhitetulip** [comment]
Hey, found out the reason. There was experimental chrome support, but it never did take off. Because of that, it was trying to open SQLITE database of chrome and something wrong was happening. I do not use Chrome hence I can't add support for it. If you want, you are welcome to add support & send a PR.

Also, the intended behaviour is that python will open your default browser, it just creates the `history.html`, please open it manually, I have no clue why it is not working.

Also the bookmark thing is not working. I'll look into it later.

I am curious as to where did you find this project and what are you using it for!
